corn_types = {
    "tipo_1": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero, necessitatibus cupiditate culpa repudiandae, voluptate repellendus minima amet autem earum impedit eum ab nemo enim laborum ullam mollitia ex! Maiores, quisquam? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem temporibus culpa explicabo dolores libero architecto voluptates quis maxime ipsam, delectus modi necessitatibus praesentium impedit illum facilis rerum aliquam quas in! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim, dolor! Aperiam totam maxime obcaecati perferendis et modi. Temporibus, quam placeat esse eum optio delectus modi quod at non exercitationem maxime?",
    "tipo_2": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero, necessitatibus cupiditate culpa repudiandae, voluptate repellendus minima amet autem earum impedit eum ab nemo enim laborum ullam mollitia ex! Maiores, quisquam? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem temporibus culpa explicabo dolores libero architecto voluptates quis maxime ipsam, delectus modi necessitatibus praesentium impedit illum facilis rerum aliquam quas in! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim, dolor! Aperiam totam maxime obcaecati perferendis et modi. Temporibus, quam placeat esse eum optio delectus modi quod at non exercitationem maxime?",
    "tipo_3": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero, necessitatibus cupiditate culpa repudiandae, voluptate repellendus minima amet autem earum impedit eum ab nemo enim laborum ullam mollitia ex! Maiores, quisquam? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem temporibus culpa explicabo dolores libero architecto voluptates quis maxime ipsam, delectus modi necessitatibus praesentium impedit illum facilis rerum aliquam quas in! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim, dolor! Aperiam totam maxime obcaecati perferendis et modi. Temporibus, quam placeat esse eum optio delectus modi quod at non exercitationem maxime?",
    "tipo_4": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero, necessitatibus cupiditate culpa repudiandae, voluptate repellendus minima amet autem earum impedit eum ab nemo enim laborum ullam mollitia ex! Maiores, quisquam? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem temporibus culpa explicabo dolores libero architecto voluptates quis maxime ipsam, delectus modi necessitatibus praesentium impedit illum facilis rerum aliquam quas in! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim, dolor! Aperiam totam maxime obcaecati perferendis et modi. Temporibus, quam placeat esse eum optio delectus modi quod at non exercitationem maxime?",
    "tipo_5": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero, necessitatibus cupiditate culpa repudiandae, voluptate repellendus minima amet autem earum impedit eum ab nemo enim laborum ullam mollitia ex! Maiores, quisquam? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem temporibus culpa explicabo dolores libero architecto voluptates quis maxime ipsam, delectus modi necessitatibus praesentium impedit illum facilis rerum aliquam quas in! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim, dolor! Aperiam totam maxime obcaecati perferendis et modi. Temporibus, quam placeat esse eum optio delectus modi quod at non exercitationem maxime?",
    
}

corn_names = {
    "tipo_1": "Nombre del maiz 01",
    "tipo_2": "Nombre del maiz 02",
    "tipo_3": "Nombre del maiz 03",
    "tipo_4": "Nombre del maiz 04",
    "tipo_5": "Nombre del maiz 05",
}
